apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: omaraliii1/cloud:auth_v1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: auth-configmap