apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30005  # Choose any available port
  selector:
    app: account
