apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: omaraliii1/cloud:account_v1
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: account-configmap