apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: omaraliii1/cloud:product_v1
        ports:
        - containerPort: 5002