apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  type: NodePort
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30004
  selector:
    app: product